/**
 * Generated by scripts/generate-pillar-index.mjs. Do not edit by hand.
 *
 * One hub pillar guide per file. 6 pillars.
 */
import type { GuidePageData } from '../../guideContent';
import { boiseHomeBuildingCostGuide } from './boise-home-building-cost-guide';
import { boiseHomeBuildingProcessGuide } from './boise-home-building-process-guide';
import { buyingLandToBuildBoise } from './buying-land-to-build-boise';
import { chooseHomeBuilderBoise } from './choose-home-builder-boise';
import { customHomeDesignGuide } from './custom-home-design-guide';
import { treasureValleyHomeBuildingGuide } from './treasure-valley-home-building-guide';

export const PILLAR_GUIDES: GuidePageData[] = [
  boiseHomeBuildingCostGuide,
  boiseHomeBuildingProcessGuide,
  buyingLandToBuildBoise,
  chooseHomeBuilderBoise,
  customHomeDesignGuide,
  treasureValleyHomeBuildingGuide,
];
