/**
 * Generated by scripts/generate-wave2-index.mjs. Do not edit by hand.
 *
 * Every hand-authored article lives in its own file in this directory and is
 * collected here. 35 posts.
 */
import type { BlogPostData } from '../../blogContent';
import { adaVsCanyonCountyPermitTimelines } from './ada-vs-canyon-county-permit-timelines';
import { aduCostBoise } from './adu-cost-boise';
import { agingInPlaceHomeDesign } from './aging-in-place-home-design';
import { allowancesExplainedNewHome } from './allowances-explained-new-home';
import { boiseBuildingPermitGuide } from './boise-building-permit-guide';
import { buildVsBuyBoise } from './build-vs-buy-boise';
import { buildingInTheBoiseFoothills } from './building-in-the-boise-foothills';
import { choosingFinishesForANewHome } from './choosing-finishes-for-a-new-home';
import { constructionLoanBasicsIdaho } from './construction-loan-basics-idaho';
import { costToBuildAHouseBoise } from './cost-to-build-a-house-boise';
import { coveredOutdoorLivingNewHome } from './covered-outdoor-living-new-home';
import { customHomeCostPerSquareFootBoise } from './custom-home-cost-per-square-foot-boise';
import { customHomeFloorPlanIdeasBoise } from './custom-home-floor-plan-ideas-boise';
import { designBuildVsGeneralContractor } from './design-build-vs-general-contractor';
import { energyEfficientHomeBuildingBoise } from './energy-efficient-home-building-boise';
import { firstMeetingWithAHomeBuilder } from './first-meeting-with-a-home-builder';
import { fixedPriceVsCostPlus } from './fixed-price-vs-cost-plus';
import { homeBuilderRedFlags } from './home-builder-red-flags';
import { howLongDoesItTakeToBuildAHouseBoise } from './how-long-does-it-take-to-build-a-house-boise';
import { howToBudgetANewHomeBoise } from './how-to-budget-a-new-home-boise';
import { howToBuyABuildableLotBoise } from './how-to-buy-a-buildable-lot-boise';
import { howToCompareBuilderBids } from './how-to-compare-builder-bids';
import { impactFeesAndUtilityConnections } from './impact-fees-and-utility-connections';
import { lotEvaluationChecklist } from './lot-evaluation-checklist';
import { luxuryHomeBuildingCostBoise } from './luxury-home-building-cost-boise';
import { multigenerationalHomeDesign } from './multigenerational-home-design';
import { newHomeWalkthroughAndWarranty } from './new-home-walkthrough-and-warranty';
import { productionVsCustomHomeBuilder } from './production-vs-custom-home-builder';
import { questionsToAskAHomeBuilder } from './questions-to-ask-a-home-builder';
import { shopHomesAndBarndominiumsIdaho } from './shop-homes-and-barndominiums-idaho';
import { singleStoryVsTwoStoryHome } from './single-story-vs-two-story-home';
import { stagesOfBuildingAHouse } from './stages-of-building-a-house';
import { wellAndSepticCostIdaho } from './well-and-septic-cost-idaho';
import { whatDrivesHomeBuildingCostsBoise } from './what-drives-home-building-costs-boise';
import { whyHomeBuildingBidsVary } from './why-home-building-bids-vary';

export const WAVE2_POSTS: BlogPostData[] = [
  adaVsCanyonCountyPermitTimelines,
  aduCostBoise,
  agingInPlaceHomeDesign,
  allowancesExplainedNewHome,
  boiseBuildingPermitGuide,
  buildVsBuyBoise,
  buildingInTheBoiseFoothills,
  choosingFinishesForANewHome,
  constructionLoanBasicsIdaho,
  costToBuildAHouseBoise,
  coveredOutdoorLivingNewHome,
  customHomeCostPerSquareFootBoise,
  customHomeFloorPlanIdeasBoise,
  designBuildVsGeneralContractor,
  energyEfficientHomeBuildingBoise,
  firstMeetingWithAHomeBuilder,
  fixedPriceVsCostPlus,
  homeBuilderRedFlags,
  howLongDoesItTakeToBuildAHouseBoise,
  howToBudgetANewHomeBoise,
  howToBuyABuildableLotBoise,
  howToCompareBuilderBids,
  impactFeesAndUtilityConnections,
  lotEvaluationChecklist,
  luxuryHomeBuildingCostBoise,
  multigenerationalHomeDesign,
  newHomeWalkthroughAndWarranty,
  productionVsCustomHomeBuilder,
  questionsToAskAHomeBuilder,
  shopHomesAndBarndominiumsIdaho,
  singleStoryVsTwoStoryHome,
  stagesOfBuildingAHouse,
  wellAndSepticCostIdaho,
  whatDrivesHomeBuildingCostsBoise,
  whyHomeBuildingBidsVary,
];
