/**
 * Branded Open Graph share cards per blog post / guide.
 *
 * Generated by `scripts/generate-og-images.mjs` — featured photo + dark overlay
 * + light editorial title + transparent seal, 1200x630 JPG at
 * `public/images/blog/{slug}-og.jpg`. Add each slug here as its card is produced;
 * blog metadata falls back to the featured hero image when a slug is absent.
 */
export const BLOG_OG_IMAGES: Record<string, string> = {
  // Costs hub
  'kitchen-remodel-cost-boise': '/images/blog/kitchen-remodel-cost-boise-og.jpg',
  'bathroom-remodel-cost-boise': '/images/blog/bathroom-remodel-cost-boise-og.jpg',
  'whole-home-remodel-cost-boise': '/images/blog/whole-home-remodel-cost-boise-og.jpg',
  'home-addition-cost-boise': '/images/blog/home-addition-cost-boise-og.jpg',
  'remodel-cost-per-square-foot-boise': '/images/blog/remodel-cost-per-square-foot-boise-og.jpg',
  'what-impacts-remodeling-costs-boise': '/images/blog/what-impacts-remodeling-costs-boise-og.jpg',
  'how-to-budget-remodel-boise': '/images/blog/how-to-budget-remodel-boise-og.jpg',
  'luxury-remodel-cost-boise': '/images/blog/luxury-remodel-cost-boise-og.jpg',
  // Contractor Selection hub
  'questions-to-ask-remodeling-contractor': '/images/blog/questions-to-ask-remodeling-contractor-og.jpg',
  'remodeling-contractor-red-flags': '/images/blog/remodeling-contractor-red-flags-og.jpg',
  'design-build-vs-general-contractor': '/images/blog/design-build-vs-general-contractor-og.jpg',
  'how-to-compare-remodeling-estimates': '/images/blog/how-to-compare-remodeling-estimates-og.jpg',
  'why-remodeling-bids-vary': '/images/blog/why-remodeling-bids-vary-og.jpg',
  'fixed-price-vs-cost-plus': '/images/blog/fixed-price-vs-cost-plus-og.jpg',
  // Kitchen hub
  'kitchen-remodel-timeline-boise': '/images/blog/kitchen-remodel-timeline-boise-og.jpg',
  'kitchen-layout-ideas-boise-homes': '/images/blog/kitchen-layout-ideas-boise-homes-og.jpg',
  'kitchen-cabinet-trends-boise': '/images/blog/kitchen-cabinet-trends-boise-og.jpg',
  'quartz-vs-quartzite-countertops': '/images/blog/quartz-vs-quartzite-countertops-og.jpg',
  'kitchen-island-design-guide': '/images/blog/kitchen-island-design-guide-og.jpg',
  'small-kitchen-remodel-ideas-boise': '/images/blog/small-kitchen-remodel-ideas-boise-og.jpg',
  'open-concept-kitchen-remodeling': '/images/blog/open-concept-kitchen-remodeling-og.jpg',
  // Bathroom hub
  'walk-in-shower-guide': '/images/blog/walk-in-shower-guide-og.jpg',
  'curbless-shower-guide': '/images/blog/curbless-shower-guide-og.jpg',
  'small-bathroom-remodel-ideas': '/images/blog/small-bathroom-remodel-ideas-og.jpg',
  'aging-in-place-bathroom-design': '/images/blog/aging-in-place-bathroom-design-og.jpg',
  'luxury-bathroom-features': '/images/blog/luxury-bathroom-features-og.jpg',
  'bathroom-layout-planning-guide': '/images/blog/bathroom-layout-planning-guide-og.jpg',
  'how-long-does-a-bathroom-remodel-take': '/images/blog/how-long-does-a-bathroom-remodel-take-og.jpg',
  // Additions / ADU hub
  'adu-cost-boise': '/images/blog/adu-cost-boise-og.jpg',
  'garage-conversions': '/images/blog/garage-conversions-og.jpg',
  'basement-finishing-boise': '/images/blog/basement-finishing-boise-og.jpg',
  'primary-suite-additions': '/images/blog/primary-suite-additions-og.jpg',
  'second-story-additions': '/images/blog/second-story-additions-og.jpg',
  'bedroom-additions': '/images/blog/bedroom-additions-og.jpg',
  'multigenerational-living-remodels': '/images/blog/multigenerational-living-remodels-og.jpg',
  'home-addition-timeline-guide': '/images/blog/home-addition-timeline-guide-og.jpg',
};

export function getBlogOgImage(slug: string): string | undefined {
  return BLOG_OG_IMAGES[slug];
}
