/**
 * Branded Open Graph share cards per blog post / guide.
 *
 * Generated by `scripts/generate-og-images.mjs` — featured photo + dark overlay
 * + light editorial title + transparent seal, 1200x630 JPG at
 * `public/images/blog/{slug}-og.jpg`. Add each slug here as its card is produced;
 * blog metadata falls back to the featured hero image when a slug is absent.
 */
export const BLOG_OG_IMAGES: Record<string, string> = {
  // Costs hub
  'kitchen-remodel-cost-boise': '/images/blog/kitchen-remodel-cost-boise-og.jpg',
  'bathroom-remodel-cost-boise': '/images/blog/bathroom-remodel-cost-boise-og.jpg',
  'whole-home-remodel-cost-boise': '/images/blog/whole-home-remodel-cost-boise-og.jpg',
  'home-addition-cost-boise': '/images/blog/home-addition-cost-boise-og.jpg',
  'remodel-cost-per-square-foot-boise': '/images/blog/remodel-cost-per-square-foot-boise-og.jpg',
  'what-impacts-remodeling-costs-boise': '/images/blog/what-impacts-remodeling-costs-boise-og.jpg',
  'how-to-budget-remodel-boise': '/images/blog/how-to-budget-remodel-boise-og.jpg',
  'luxury-remodel-cost-boise': '/images/blog/luxury-remodel-cost-boise-og.jpg',
  // Contractor Selection hub
  'questions-to-ask-remodeling-contractor': '/images/blog/questions-to-ask-remodeling-contractor-og.jpg',
  'remodeling-contractor-red-flags': '/images/blog/remodeling-contractor-red-flags-og.jpg',
  'design-build-vs-general-contractor': '/images/blog/design-build-vs-general-contractor-og.jpg',
  'how-to-compare-remodeling-estimates': '/images/blog/how-to-compare-remodeling-estimates-og.jpg',
};

export function getBlogOgImage(slug: string): string | undefined {
  return BLOG_OG_IMAGES[slug];
}
