/**
 * Per-slug hero imagery for blog posts and guides.
 *
 * Generated by scripts/generate-blog-image-registry.ts from the content layer.
 * Do not hand-edit. Change the assignment table in that script and re-run
 * `npm run images:blog`.
 */

export type BlogImageSource = 'construction';

export interface BlogImageEntry {
  hero: string;
  thumbnail?: string;
  alt: string;
  topicTags: string[];
  source: BlogImageSource;
}

export const BLOG_IMAGE_REGISTRY: Record<string, BlogImageEntry> = {
  'ada-vs-canyon-county-permit-timelines': {
    hero: '/images/construction/building-permit-documents.webp',
    alt: 'Residential building permit packet with stamped site and floor plans, an application, and an approval stamp on a desk',
    topicTags: ["permits","ada county","canyon county","building process","home"],
    source: 'construction',
  },
  'adu-cost-boise': {
    hero: '/images/construction/semi-custom-home.webp',
    alt: 'Newly built single-story semi-custom home on a serviced subdivision lot in Meridian, Idaho',
    topicTags: ["adu","accessory dwelling unit","new construction","cost","boise"],
    source: 'construction',
  },
  'aging-in-place-home-design': {
    hero: '/images/construction/accessible-primary-bathroom.webp',
    alt: 'Accessible primary bathroom in a new Idaho home with a curbless walk-in shower, fold-down bench, and a floating vanity',
    topicTags: ["aging in place","accessibility","home design","floor plans","new construction"],
    source: 'construction',
  },
  'allowances-explained-new-home': {
    hero: '/images/construction/finish-selections-board.webp',
    alt: 'Flat-lay of new-home finish selections: quartz and wood samples, tile, cabinet doors, a paint deck, and matte black hardware',
    topicTags: ["allowances","contracts","budget","new construction","home"],
    source: 'construction',
  },
  'boise-building-permit-guide': {
    hero: '/images/construction/building-permit-documents.webp',
    alt: 'Residential building permit packet with stamped site and floor plans, an application, and an approval stamp on a desk',
    topicTags: ["permits","new construction","boise","building process","home"],
    source: 'construction',
  },
  'build-vs-buy-boise': {
    hero: '/images/construction/new-neighborhood-street.webp',
    alt: 'Street of recently finished new-construction homes with young trees and fresh sidewalks in a Treasure Valley subdivision',
    topicTags: ["build vs buy","planning","treasure valley","cost","home"],
    source: 'construction',
  },
  'building-in-the-boise-foothills': {
    hero: '/images/construction/foothills-building-site.webp',
    alt: 'Terraced building pad cut into a Boise foothills hillside with a boulder retaining wall and access road',
    topicTags: ["foothills","land","boise","cost","slope"],
    source: 'construction',
  },
  'choosing-finishes-for-a-new-home': {
    hero: '/images/construction/new-home-kitchen.webp',
    alt: 'Newly completed kitchen in a custom home with a quartz island and full-height tile backsplash',
    topicTags: ["finishes","selections","new construction","budget","home"],
    source: 'construction',
  },
  'construction-loan-basics-idaho': {
    hero: '/images/construction/line-item-budget.webp',
    alt: 'Line-item construction budget and draw schedule on a desk beside a wooden architectural model',
    topicTags: ["financing","construction loan","idaho","planning","home"],
    source: 'construction',
  },
  'cost-to-build-a-house-boise': {
    hero: '/images/construction/custom-home-exterior.webp',
    alt: 'Newly completed custom home with board-and-batten siding and a covered porch on a Treasure Valley lot',
    topicTags: ["cost","custom home","boise","new construction","home"],
    source: 'construction',
  },
  'covered-outdoor-living-new-home': {
    hero: '/images/construction/covered-outdoor-living.webp',
    alt: 'Deep covered patio with a timber ceiling and outdoor kitchen attached to a newly built Idaho home',
    topicTags: ["outdoor living","covered patio","home design","new construction","treasure valley"],
    source: 'construction',
  },
  'custom-home-cost-per-square-foot-boise': {
    hero: '/images/construction/home-under-framing.webp',
    alt: 'New house under construction with wall framing and roof trusses in place on an Idaho building site',
    topicTags: ["cost","cost per square foot","boise","custom home","home"],
    source: 'construction',
  },
  'custom-home-floor-plan-ideas-boise': {
    hero: '/images/construction/blueprints-drafting.webp',
    alt: 'Rolled residential blueprints, an architect\'s scale, and a basswood study model on a drafting desk',
    topicTags: ["floor plans","home design","new construction","boise","treasure valley"],
    source: 'construction',
  },
  'design-build-vs-general-contractor': {
    hero: '/images/construction/custom-home-dusk-exterior.webp',
    alt: 'Newly completed modern farmhouse custom home glowing at dusk on a Treasure Valley lot with the Boise foothills behind',
    topicTags: ["choosing a builder","design-build","boise","new construction","choosing"],
    source: 'construction',
  },
  'energy-efficient-home-building-boise': {
    hero: '/images/construction/insulation-and-air-sealing.webp',
    alt: 'Wall cavities insulated and air sealed in a new Idaho home before drywall goes up',
    topicTags: ["energy efficiency","high performance","hvac","insulation","new construction"],
    source: 'construction',
  },
  'first-meeting-with-a-home-builder': {
    hero: '/images/construction/site-meeting.webp',
    alt: 'Builder reviewing plans with homeowners in front of a partially framed house on an Idaho site',
    topicTags: ["consultation","new construction","boise","getting started","home"],
    source: 'construction',
  },
  'fixed-price-vs-cost-plus': {
    hero: '/images/construction/builder-bid-comparison.webp',
    alt: 'Three residential construction bids fanned out on a desk with a highlighter marking line items for comparison',
    topicTags: ["choosing a builder","contracts","boise","new construction","choosing"],
    source: 'construction',
  },
  'home-builder-red-flags': {
    hero: '/images/construction/planning-consultation-table.webp',
    alt: 'New-home planning consultation at a kitchen table with printed floor plans and a tablet showing a 3D house model',
    topicTags: ["choosing a builder","contracts","boise","new construction","choosing"],
    source: 'construction',
  },
  'how-long-does-it-take-to-build-a-house-boise': {
    hero: '/images/construction/mechanical-rough-in.webp',
    alt: 'Open stud walls with plumbing, electrical, and ductwork roughed in before drywall in a new home',
    topicTags: ["new construction","timeline","boise","building process","home"],
    source: 'construction',
  },
  'how-to-budget-a-new-home-boise': {
    hero: '/images/construction/line-item-budget.webp',
    alt: 'Line-item construction budget and draw schedule on a desk beside a wooden architectural model',
    topicTags: ["budget","cost","planning","boise","home"],
    source: 'construction',
  },
  'how-to-buy-a-buildable-lot-boise': {
    hero: '/images/construction/buildable-lot.webp',
    alt: 'Vacant buildable lot on the Treasure Valley floor with a survey stake, power line, and irrigation ditch',
    topicTags: ["land","lots","boise","site work","due diligence"],
    source: 'construction',
  },
  'how-to-compare-builder-bids': {
    hero: '/images/construction/builder-bid-comparison.webp',
    alt: 'Three residential construction bids fanned out on a desk with a highlighter marking line items for comparison',
    topicTags: ["choosing a builder","budgeting","boise","new construction","choosing"],
    source: 'construction',
  },
  'impact-fees-and-utility-connections': {
    hero: '/images/construction/rural-site-work.webp',
    alt: 'Well drilling rig and septic drainfield excavation underway on a rural Idaho building site',
    topicTags: ["impact fees","permits","utilities","ada county","canyon county"],
    source: 'construction',
  },
  'lot-evaluation-checklist': {
    hero: '/images/construction/buildable-lot.webp',
    alt: 'Vacant buildable lot on the Treasure Valley floor with a survey stake, power line, and irrigation ditch',
    topicTags: ["land","lots","checklist","due diligence","treasure valley"],
    source: 'construction',
  },
  'luxury-home-building-cost-boise': {
    hero: '/images/construction/great-room-evening.webp',
    alt: 'Finished great room in a new Idaho home at dusk with a tile fireplace, beamed ceiling, and a steel-frame window wall',
    topicTags: ["luxury","cost","custom home","boise","home"],
    source: 'construction',
  },
  'multigenerational-home-design': {
    hero: '/images/construction/two-story-home-exterior.webp',
    alt: 'Newly built two-story craftsman home with stone wainscot and a covered front porch on a Meridian, Idaho lot',
    topicTags: ["multigenerational","home design","floor plans","accessibility","new construction"],
    source: 'construction',
  },
  'new-home-walkthrough-and-warranty': {
    hero: '/images/construction/staircase-foyer.webp',
    alt: 'Finished entry staircase in a new Idaho home with white oak treads, black metal balusters, and a two-story foyer',
    topicTags: ["warranty","walkthrough","punch list","new construction","home"],
    source: 'construction',
  },
  'production-vs-custom-home-builder': {
    hero: '/images/construction/new-neighborhood-street.webp',
    alt: 'Street of recently finished new-construction homes with young trees and fresh sidewalks in a Treasure Valley subdivision',
    topicTags: ["choosing a builder","custom homes","boise","new construction","choosing"],
    source: 'construction',
  },
  'questions-to-ask-a-home-builder': {
    hero: '/images/construction/plans-and-selections.webp',
    alt: 'Residential floor plan and elevation drawings laid out with flooring, countertop, and paint samples',
    topicTags: ["choosing a builder","contracts","boise","new construction","choosing"],
    source: 'construction',
  },
  'shop-homes-and-barndominiums-idaho': {
    hero: '/images/construction/shop-home-barndominium.webp',
    alt: 'Shop home combining a finished living wing with an attached shop under one metal roof on Idaho acreage',
    topicTags: ["barndominium","shop home","post frame","new construction","idaho"],
    source: 'construction',
  },
  'single-story-vs-two-story-home': {
    hero: '/images/construction/two-story-home-exterior.webp',
    alt: 'Newly built two-story craftsman home with stone wainscot and a covered front porch on a Meridian, Idaho lot',
    topicTags: ["floor plans","home design","cost","new construction","treasure valley"],
    source: 'construction',
  },
  'stages-of-building-a-house': {
    hero: '/images/construction/foundation-and-excavation.webp',
    alt: 'Freshly poured concrete foundation and stem walls outlining a new home on a flat valley lot',
    topicTags: ["new construction","building process","boise","construction stages","home"],
    source: 'construction',
  },
  'well-and-septic-cost-idaho': {
    hero: '/images/construction/rural-site-work.webp',
    alt: 'Well drilling rig and septic drainfield excavation underway on a rural Idaho building site',
    topicTags: ["land","well","septic","rural","site work"],
    source: 'construction',
  },
  'what-drives-home-building-costs-boise': {
    hero: '/images/construction/foundation-and-excavation.webp',
    alt: 'Freshly poured concrete foundation and stem walls outlining a new home on a flat valley lot',
    topicTags: ["cost","new construction","boise","planning","home"],
    source: 'construction',
  },
  'why-home-building-bids-vary': {
    hero: '/images/construction/builder-bid-comparison.webp',
    alt: 'Three residential construction bids fanned out on a desk with a highlighter marking line items for comparison',
    topicTags: ["choosing a builder","budgeting","boise","new construction","choosing"],
    source: 'construction',
  },
  'boise-home-building-cost-guide': {
    hero: '/images/construction/line-item-budget.webp',
    alt: 'Line-item construction budget and draw schedule on a desk beside a wooden architectural model',
    topicTags: ["cost","budgeting","custom home","new construction","boise"],
    source: 'construction',
  },
  'boise-home-building-process-guide': {
    hero: '/images/construction/home-under-framing.webp',
    alt: 'New house under construction with wall framing and roof trusses in place on an Idaho building site',
    topicTags: ["building process","new construction","boise","permits","treasure valley"],
    source: 'construction',
  },
  'buying-land-to-build-boise': {
    hero: '/images/construction/rural-acreage-parcel.webp',
    alt: 'Vacant rural acreage building parcel in Canyon County, Idaho with a survey stake and desert mountains on the horizon',
    topicTags: ["land","lots","buildable lot","site work","due diligence"],
    source: 'construction',
  },
  'choose-home-builder-boise': {
    hero: '/images/construction/site-meeting.webp',
    alt: 'Builder reviewing plans with homeowners in front of a partially framed house on an Idaho site',
    topicTags: ["choosing a builder","home builder","contracts","design-build","boise"],
    source: 'construction',
  },
  'custom-home-design-guide': {
    hero: '/images/construction/blueprints-drafting.webp',
    alt: 'Rolled residential blueprints, an architect\'s scale, and a basswood study model on a drafting desk',
    topicTags: ["home design","floor plans","custom homes","new construction","treasure valley"],
    source: 'construction',
  },
  'treasure-valley-home-building-guide': {
    hero: '/images/construction/new-neighborhood-street.webp',
    alt: 'Street of recently finished new-construction homes with young trees and fresh sidewalks in a Treasure Valley subdivision',
    topicTags: ["treasure valley","new construction","ada county","canyon county","home building"],
    source: 'construction',
  },
  'boise-home-building-guide': {
    hero: '/images/construction/custom-home-exterior.webp',
    alt: 'Newly completed custom home with board-and-batten siding and a covered porch on a Treasure Valley lot',
    topicTags: ["boise","idaho","new construction","treasure"],
    source: 'construction',
  },
  'meridian-home-building-guide': {
    hero: '/images/construction/semi-custom-home.webp',
    alt: 'Newly built single-story semi-custom home on a serviced subdivision lot in Meridian, Idaho',
    topicTags: ["meridian","idaho","new construction","treasure"],
    source: 'construction',
  },
  'eagle-home-building-guide': {
    hero: '/images/construction/new-home-interior.webp',
    alt: 'Finished great room in a new custom home with vaulted ceiling, stone fireplace, and foothills views',
    topicTags: ["eagle","idaho","new construction","treasure"],
    source: 'construction',
  },
  'kuna-home-building-guide': {
    hero: '/images/construction/rural-site-work.webp',
    alt: 'Well drilling rig and septic drainfield excavation underway on a rural Idaho building site',
    topicTags: ["kuna","idaho","new construction","treasure"],
    source: 'construction',
  },
  'star-home-building-guide': {
    hero: '/images/construction/buildable-lot.webp',
    alt: 'Vacant buildable lot on the Treasure Valley floor with a survey stake, power line, and irrigation ditch',
    topicTags: ["star","idaho","new construction","treasure"],
    source: 'construction',
  },
  'middleton-home-building-guide': {
    hero: '/images/construction/foundation-and-excavation.webp',
    alt: 'Freshly poured concrete foundation and stem walls outlining a new home on a flat valley lot',
    topicTags: ["middleton","idaho","new construction","treasure"],
    source: 'construction',
  },
  'nampa-home-building-guide': {
    hero: '/images/construction/semi-custom-home.webp',
    alt: 'Newly built single-story semi-custom home on a serviced subdivision lot in Meridian, Idaho',
    topicTags: ["nampa","idaho","new construction","treasure"],
    source: 'construction',
  },
  'caldwell-home-building-guide': {
    hero: '/images/construction/rural-acreage-parcel.webp',
    alt: 'Vacant rural acreage building parcel in Canyon County, Idaho with a survey stake and desert mountains on the horizon',
    topicTags: ["caldwell","idaho","new construction","treasure"],
    source: 'construction',
  },
  'eagle-foothills-home-building-guide': {
    hero: '/images/construction/foothills-building-site.webp',
    alt: 'Terraced building pad cut into a Boise foothills hillside with a boulder retaining wall and access road',
    topicTags: ["eagle","the eagle foothills","idaho","new construction","treasure"],
    source: 'construction',
  },
  'hidden-springs-home-building-guide': {
    hero: '/images/construction/custom-home-exterior.webp',
    alt: 'Newly completed custom home with board-and-batten siding and a covered porch on a Treasure Valley lot',
    topicTags: ["eagle","hidden springs","idaho","new construction","treasure"],
    source: 'construction',
  },
  'harris-ranch-home-building-guide': {
    hero: '/images/construction/great-room-evening.webp',
    alt: 'Finished great room in a new Idaho home at dusk with a tile fireplace, beamed ceiling, and a steel-frame window wall',
    topicTags: ["boise","harris ranch","idaho","new construction","treasure"],
    source: 'construction',
  },
};

export const HUB_HERO_IMAGES: Record<string, string> = {
  'home-building-costs': '/images/construction/line-item-budget.webp',
  'choosing-a-builder': '/images/construction/site-meeting.webp',
  'home-building-process': '/images/construction/home-under-framing.webp',
  'land-and-lots': '/images/construction/buildable-lot.webp',
  'home-design-and-plans': '/images/construction/plans-and-selections.webp',
  'treasure-valley-locations': '/images/construction/custom-home-exterior.webp',
};

/** Retained for the setup script's interface; nothing is copied any more. */
export const BLOG_ASSET_COPY_MAP: Record<string, string> = {};
